### ISSUE TITLE
Master and main are entirely different commit histories.

### ISSUE THREAD

**Issue by ahmed82** [ahmed82/go-movies#2]
master and main are entirely different commit histories.

**Comment by ahmed82** [comment]
This one works:
```
git checkout master   
git branch main master -f    
git checkout main  
git push origin main -f
```

**Comment by ahmed82** [comment]
Another solution not tested yet:
````
git branch new_branch
git checkout new_branch
git merge develop --allow-unrelated-histories
```

**Comment by ahmed82** [comment]
Another Solutions not tested yet:

If you redo your commits on top of the original history, you should then be able to compare the branches. There are several different ways that you can redo your commits, including
```
git rebase --onto
```
and
```
git cherry-pick
```
You also can redo each commit manually, if you have to.

**Comment by NicoJL** [comment]
> Another solution not tested yet:
> 
> ```
> git branch new_branch
> git checkout new_branch
> git merge develop --allow-unrelated-histories
> ```
> ```

Thank you
